# Generated by Django 3.2.2 on 2021-07-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fruitslist',
        ),
    ]
