# Generated by Django 3.2.2 on 2021-06-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruitslist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fruitsName', models.CharField(max_length=20)),
                ('memo', models.CharField(max_length=200)),
            ],
        ),
    ]
