# Generated by Django 3.2.2 on 2021-07-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nm', models.CharField(max_length=30)),
                ('del_flg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='M_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('del_flg', models.CharField(max_length=1)),
            ],
        ),
    ]
