# Generated by Django 3.2.2 on 2021-07-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_t_order_details_t_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_items',
            name='id',
        ),
        migrations.RemoveField(
            model_name='m_users',
            name='id',
        ),
        migrations.AddField(
            model_name='m_items',
            name='item_no',
            field=models.IntegerField(default=20210731, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_users',
            name='user_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
