# Generated by Django 3.2.2 on 2021-08-09 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210731_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_items',
            name='register_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='m_items',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
