# Generated by Django 3.2.2 on 2021-08-09 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210809_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_users',
            name='register_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='m_users',
            name='version',
            field=models.IntegerField(default=20210809),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_order_details',
            name='register_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='t_order_details',
            name='version',
            field=models.IntegerField(default=20210809),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_orders',
            name='register_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='t_orders',
            name='version',
            field=models.IntegerField(default=20210809),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m_items',
            name='version',
            field=models.IntegerField(default=20210809),
            preserve_default=False,
        ),
    ]
